Repository instrumentisto/medea, pull requests merged in 2019-07, with the labels that each got.

#22 WIP: Implement signalling and media management in Jason
  .clippy.toml
  Cargo.lock
  Makefile
  docs/rfc/0002-webrc-client-api.md
  jason/Cargo.toml
  jason/e2e-demo/js/index.js
  jason/src/api/connection.rs
  jason/src/api/jason.rs
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/lib.rs
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/src/media/stream.rs
  jason/src/media/stream_request.rs
  jason/src/media/track.rs
  jason/src/peer/conn.rs
  jason/src/peer/ice_server.rs
  jason/src/peer/media.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/src/utils/callback.rs
  jason/src/utils/errors.rs
  jason/src/utils/event_listener.rs
  jason/src/utils/mod.rs
  proto/client-api/src/lib.rs
  signaling_test.html
  src/api/client/rpc_connection.rs
  src/api/client/server.rs
  src/main.rs
  src/media/mod.rs
  src/media/peer.rs
  src/media/track.rs
  src/signalling/participants.rs
  src/signalling/room.rs
  src/turn/repo.rs
  src/turn/service.rs
Labels: feature, k::api, k::design

#35 Dockerize Medea
  .dockerignore
  .editorconfig
  .env
  Cargo.lock
  Cargo.toml
  Dockerfile
  Makefile
  config.toml
  hooks/post_push
  src/api/client/server.rs
  src/conf/log.rs
  src/conf/mod.rs
  src/conf/rpc.rs
  src/conf/server.rs
  src/conf/turn.rs
  src/main.rs
Labels: feature, k::config, k::deploy

#30 Graceful shutdown
  Cargo.lock
  Cargo.toml
  config.toml
  src/api/client/server.rs
  src/conf/mod.rs
  src/conf/shutdown.rs
  src/main.rs
  src/shutdown.rs
  src/signalling/participants.rs
  src/signalling/room.rs
  src/signalling/room_repo.rs
Labels: feature, k::deploy

#37 Fix OsSignal for GracefulShutdown, fix default shutdown.timeout in docs
  config.toml
  src/api/client/server.rs
  src/shutdown.rs
  src/signalling/room.rs
Labels: enhancement, k::deploy

#38 Implement and dockerize demo application (#34)
  .editorconfig
  .yarnrc
  Makefile
  jason/demo/.gitignore
  jason/demo/Dockerfile
  jason/demo/README.md
  jason/demo/conf/nginx.vh.conf
  jason/demo/docker-compose.yml
  jason/demo/index.html
  jason/demo/package.json
  jason/demo/yarn.lock
  src/log/mod.rs
  src/main.rs
  src/signalling/participants.rs
  src/signalling/room.rs
  src/turn/service.rs
Labels: feature, k::deploy
