Repository instrumentisto/medea, pull requests merged in 2019-10, with the labels that each got.

#56 Dockerize Jason's browser unit testing
  .env
  .travis.yml
  Cargo.lock
  Makefile
  jason/webdriver.json
Labels: enhancement, k::testing

#59 Improve Medea's Dockerfile to cache built dependencies
  .dockerignore
  Dockerfile
  Makefile
Labels: enhancement, k::performance, k::toolchain

#46 Expose MediaDevices and create media stream from user constraints (#45)
  .clippy.toml
  Cargo.lock
  Makefile
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/demo/index.html
  jason/e2e-demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/lib.rs
  jason/src/media/constraints.rs
  jason/src/media/device_info.rs
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/src/media/stream.rs
  jason/src/media/stream_request.rs
  jason/src/media/track.rs
  jason/src/peer/conn.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/rpc/mod.rs
  jason/src/utils/mod.rs
  jason/tests/media/constraints.rs
  jason/tests/media/manager.rs
  jason/tests/media/mod.rs
  jason/tests/peer/media.rs
  jason/tests/utils/mod.rs
  jason/tests/web.rs
  jason/webdriver.json
Labels: feature, k::api, k::design

#60 Jason: update to wasm-bindgen-futures v0.4 with async/.await support
  .travis.yml
  Cargo.lock
  Makefile
  crates/medea-macro/src/dispatchable.rs
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/src/media/manager.rs
  jason/src/peer/conn.rs
  jason/src/peer/media.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/src/utils/errors.rs
  jason/tests/api/room.rs
  jason/tests/media/constraints.rs
  jason/tests/media/manager.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  jason/tests/web.rs
  jason/webdriver.json
Labels: enhancement, k::refactor
