Repository instrumentisto/medea, pull requests merged in 2019-06, with the labels that each got.

#26 Add macro for convenient dispatch Jason room events
  Cargo.lock
  crates/medea-macro/Cargo.toml
  crates/medea-macro/src/dispatchable.rs
  crates/medea-macro/src/lib.rs
  jason/src/api/room.rs
  proto/client-api/Cargo.toml
  proto/client-api/src/lib.rs
Labels: enhancement, k: design

#20 WIP: Add coturn integration
  .env
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  config.toml
  dev/coturn/redis.conf
  dev/coturn/turnserver.conf
  docker-compose.yml
  jason/src/api/room.rs
  proto/client-api/src/lib.rs
  signaling_test.html
  src/api/client/rpc_connection.rs
  src/api/client/server.rs
  src/api/control/member.rs
  src/conf/mod.rs
  src/conf/server.rs
  src/conf/turn.rs
  src/main.rs
  src/media/ice_user.rs
  src/media/mod.rs
  src/signalling/participants.rs
  src/signalling/peers.rs
  src/signalling/room.rs
  src/turn/mod.rs
  src/turn/repo.rs
  src/turn/service.rs
Labels: feature, k::deploy

#31 Bump version of actix and actix_web
  .clippy.toml
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  docker-compose.yml
  jason/src/utils/event_listener.rs
  src/api/client/server.rs
  src/api/client/session.rs
  src/main.rs
  src/signalling/participants.rs
  src/signalling/room.rs
  src/turn/service.rs
Labels: enhancement, k::toolchain
