Repository instrumentisto/medea, pull requests merged in 2019-11, with the labels that each got.

#54 Add ability to inject the local MediaStream to Room (#45)
  .clippy.toml
  Cargo.lock
  Makefile
  crates/medea-macro/src/lib.rs
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/demo/chart/medea-demo/Chart.yaml
  jason/demo/chart/medea-demo/templates/deployment.server.yaml
  jason/demo/index.html
  jason/demo/staging.vals.yaml
  jason/e2e-demo/js/index.js
  jason/src/api/connection.rs
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/lib.rs
  jason/src/media/constraints.rs
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/src/media/stream_request.rs
  jason/src/peer/conn.rs
  jason/src/peer/media.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/peer/stream.rs
  jason/src/peer/stream_request.rs
  jason/src/peer/track.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/src/utils/callback.rs
  jason/src/utils/errors.rs
  jason/src/utils/event_listener.rs
  jason/src/utils/mod.rs
  jason/tests/api/room.rs
  jason/tests/media/constraints.rs
  jason/tests/media/manager.rs
  jason/tests/mock_navigator.js
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  jason/tests/utils/mod.rs
  jason/tests/web.rs
  mock/control-api/src/main.rs
  proto/client-api/src/lib.rs
  src/api/client/session.rs
  src/api/control/error_codes.rs
  src/api/control/grpc/server.rs
  src/lib.rs
  src/signalling/elements/endpoints/webrtc/play_endpoint.rs
  src/signalling/participants.rs
  src/turn/repo.rs
  src/turn/service.rs
Labels: feature, k::api, k::design

#64 Use stable Rust in Jason
  .travis.yml
  Cargo.lock
  Cargo.toml
  Makefile
  jason/Cargo.toml
  jason/Dockerfile
  jason/src/api/mod.rs
  jason/src/lib.rs
  mock/control-api/src/main.rs
  proto/client-api/src/lib.rs
  src/lib.rs
Labels: enhancement, k::toolchain

#66 Output type of fns in dispatchable macro's handler trait
  Cargo.lock
  Cargo.toml
  crates/medea-macro/CHANGELOG.md
  crates/medea-macro/Cargo.toml
  crates/medea-macro/src/dispatchable.rs
  crates/medea-macro/src/lib.rs
  jason/Cargo.toml
  jason/src/api/room.rs
  proto/client-api/Cargo.toml
  proto/client-api/src/lib.rs
  src/signalling/room.rs
Labels: enhancement, k::refactor, k::toolchain

#65 Speed Up Travis CI
  .travis.yml
  Cargo.lock
Labels: enhancement, k::performance, k::testing, k::toolchain

#67 Synchronise 'wasm-bindgen-cli' on CI with 'wasm-bindgen' from 'Cargo.lock'
  .travis.yml
  Cargo.lock
Labels: enhancement, k::testing, k::toolchain

#69 Tests for Jason's 'WebsocketRpcClient'
  Cargo.lock
  Cargo.toml
  jason/Cargo.toml
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/tests/rpc/mod.rs
  jason/tests/web.rs
  proto/client-api/src/lib.rs
Labels: enhancement, feature, k::refactor, k::testing

#71 Emit `IceConnectionStateChanged` client metrics
  Cargo.lock
  docs/rfc/0002-webrc-client-api.md
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/src/peer/conn.rs
  jason/src/peer/mod.rs
  jason/tests/peer/mod.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/api/client/session.rs
  src/signalling/room.rs
Labels: feature, k::api, k::monitoring

#72 Improve Jason demo CSS
  Cargo.lock
  Cargo.toml
  jason/demo/docker-compose.yml
  jason/demo/index.html
  jason/demo/staging.vals.yaml
  src/main.rs
Labels: enhancement, k::refactor

#68 Add trace information to errors of WebClient (#62)
  .clippy.toml
  Cargo.lock
  crates/medea-macro/CHANGELOG.md
  crates/medea-macro/Cargo.toml
  crates/medea-macro/src/js_caused.rs
  crates/medea-macro/src/lib.rs
  crates/medea-macro/tests/js_caused.rs
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/e2e-demo/package.json
  jason/src/api/room.rs
  jason/src/media/device_info.rs
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/src/peer/conn.rs
  jason/src/peer/media.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/peer/stream_request.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/src/utils/errors.rs
  jason/src/utils/event_listener.rs
  jason/src/utils/mod.rs
  jason/tests/api/room.rs
  jason/tests/media/manager.rs
  jason/tests/peer/media.rs
  jason/tests/rpc/mod.rs
  jason/tests/rpc/websocket.rs
  jason/tests/web.rs
Labels: enhancement, feature, k::design, k::refactor
