Repository instrumentisto/medea, pull requests merged in 2020-06, with the labels that each got.

#108 Update demo Nginx config (#27)
  jason/demo/chart/medea-demo/Chart.yaml
  jason/demo/chart/medea-demo/conf/nginx.vh.conf
  jason/demo/staging.vals.yaml
Labels: enhancement, k::deploy

#107 Upgrade deps and Rust version (#27)
  Cargo.lock
  Makefile
  crates/medea-reactive/src/field/cell.rs
  jason/e2e-demo/.gitignore
  jason/e2e-demo/package.json
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/reconnect_handle.rs
  proto/control-api/src/grpc/mod.rs
Labels: enhancement, k::toolchain

#106 Configure WebRtcPublishEndpoint media type by Control API (#27)
  Cargo.lock
  _dev/specs/all-media-types-required-call.yml
  _dev/specs/audio-call.yml
  crates/medea-macro/src/dispatchable.rs
  crates/medea-macro/src/enum_delegate.rs
  jason/CHANGELOG.md
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/api/connection.rs
  jason/src/api/room.rs
  jason/src/media/constraints.rs
  jason/src/peer/conn.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  jason/src/peer/stream_request.rs
  jason/src/rpc/mod.rs
  jason/src/utils/errors.rs
  jason/tests/api/room.rs
  jason/tests/media/constraints.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  jason/tests/rpc/mod.rs
  jason/tests/web.rs
  mock/control-api/Cargo.toml
  mock/control-api/src/api/endpoint.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  proto/control-api/CHANGELOG.md
  proto/control-api/src/grpc/api.proto
  proto/control-api/src/grpc/api.rs
  src/api/control/callback/mod.rs
  src/api/control/endpoints/webrtc_publish_endpoint.rs
  src/api/control/mod.rs
  src/media/peer.rs
  src/media/track.rs
  src/signalling/elements/endpoints/webrtc/publish_endpoint.rs
  src/signalling/elements/member.rs
  src/signalling/participants.rs
  src/signalling/peers/metrics.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  tests/e2e/grpc_control_api/mod.rs
  tests/e2e/signalling/mod.rs
Labels: feature, k::api

#110 Refactor PeersService to more idiomatic async/.await (#27)
  Cargo.lock
  src/media/peer.rs
  src/signalling/elements/endpoints/mod.rs
  src/signalling/elements/endpoints/webrtc/play_endpoint.rs
  src/signalling/elements/endpoints/webrtc/publish_endpoint.rs
  src/signalling/peers/metrics.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
Labels: enhancement, k::refactor, k::testing

#105 Implement dynamic tracks addition with renegotiation (#27)
  CHANGELOG.md
  Cargo.lock
  docs/rfc/0002-webrtc-client-api.md
  jason/CHANGELOG.md
  jason/src/api/room.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/mod.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/api/client/rpc_connection.rs
  src/media/mod.rs
  src/media/peer.rs
  src/signalling/elements/member.rs
  src/signalling/peers/mod.rs
  src/signalling/peers/traffic_watcher.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
  src/utils/actix_try_join_all.rs
  src/utils/mod.rs
  tests/e2e/grpc_control_api/create.rs
  tests/e2e/main.rs
  tests/e2e/signalling/mod.rs
  tests/e2e/signalling/pub_sub_signallng.rs
Labels: feature, k::api, k::design

#112 Improve #[dispatchable] macro
  Cargo.lock
  crates/medea-macro/CHANGELOG.md
  crates/medea-macro/Cargo.toml
  crates/medea-macro/src/dispatchable.rs
  crates/medea-macro/src/lib.rs
Labels: enhancement, feature, k::refactor

#113 Refactor Jason to more idiomatic async/.await
  Cargo.lock
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/src/media/manager.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  proto/client-api/Cargo.toml
  proto/client-api/src/lib.rs
Labels: enhancement, k::refactor
