Repository instrumentisto/medea, pull requests merged in 2020-12, with the labels that each got.

#158 Add width and height constraints configuration to Jason (#27)
  .clippy.toml
  Cargo.lock
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/src/media/constraints.rs
Labels: feature, k::api

#161 Check tracks state after getUserMedia()/getDisplayMedia() (#27)
  Cargo.lock
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/tests/media/manager.rs
  jason/tests/mock_navigator.js
  jason/tests/web.rs
Labels: enhancement, k::api

#159 Implement subscription on update processing end in 'medea-reactive' (#27, #47)
  Cargo.lock
  crates/medea-reactive/CHANGELOG.md
  crates/medea-reactive/src/collections/hash_map.rs
  crates/medea-reactive/src/collections/hash_set.rs
  crates/medea-reactive/src/collections/mod.rs
  crates/medea-reactive/src/collections/vec.rs
  crates/medea-reactive/src/field/mod.rs
  crates/medea-reactive/src/lib.rs
  crates/medea-reactive/src/subscribers_store/common.rs
  crates/medea-reactive/src/subscribers_store/mod.rs
  crates/medea-reactive/src/subscribers_store/progressable/guarded.rs
  crates/medea-reactive/src/subscribers_store/progressable/mod.rs
Labels: feature, k::api, k::design

#162 Migrate to GitHub Actions
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/release-medea-demo-helm-chart.yml
  .travis.yml
  Dockerfile
  Makefile
  README.md
  RELEASING.md
  hooks/post_push
  jason/Dockerfile
  jason/demo/Dockerfile
  jason/tests/api/mod.rs
  jason/tests/rpc/rpc_session.rs
  mock/control-api/Dockerfile
  proto/client-api/src/lib.rs
  tests/e2e/signalling/mod.rs
Labels: feature, k::toolchain

#160 Free media devices before switch in Jason (#27)
  Cargo.lock
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/media/constraints.rs
  jason/src/media/manager.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  jason/src/peer/transceiver.rs
  jason/tests/api/room.rs
  jason/tests/web.rs
Labels: enhancement, feature, k::api, k::refactor

#166 Disable PeerTrafficWatcher and CoturnMetricsService
  Cargo.lock
  Cargo.toml
  Makefile
  src/api/control/member.rs
  src/signalling/peers/traffic_watcher.rs
  src/signalling/room_service.rs
  src/turn/coturn_metrics.rs
  src/turn/service.rs
Labels: enhancement, k::design, k::monitoring, rollback
