Repository instrumentisto/medea, pull requests merged in 2020-09, with the labels that each got.

#132 Implement call quality estimation (#27)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/rfc/0002-webrtc-client-api.md
  jason/CHANGELOG.md
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/e2e-demo/video-call.html
  jason/src/api/connection.rs
  jason/src/api/room.rs
  jason/tests/peer/mod.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  proto/client-api/src/stats.rs
  src/signalling/peers/metrics.rs
  src/signalling/peers/mod.rs
  src/signalling/peers/quality_meter.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/mod.rs
  src/signalling/room/peer_events_handler.rs
  tests/e2e/signalling/mod.rs
Labels: feature, k::api, k::design, k::monitoring

#129 Use 'log' and 'wasm-logger' crates for Jason logging (#27)
  .travis.yml
  Cargo.lock
  jason/Cargo.toml
  jason/e2e-demo/js/index.js
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/peer/conn.rs
  jason/src/peer/mod.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/websocket.rs
  jason/src/utils/errors.rs
  jason/src/utils/event_listener.rs
  jason/src/utils/mod.rs
Labels: enhancement, k::logging, k::refactor

#130 Implement Receiver muting before call (#27)
  Cargo.lock
  Makefile
  jason/e2e-demo/js/index.js
  jason/e2e-demo/video-call.html
  jason/src/api/room.rs
  jason/src/media/constraints.rs
  jason/src/media/mod.rs
  jason/src/media/stream.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  jason/tests/rpc/mod.rs
  jason/tests/web.rs
  proto/client-api/src/lib.rs
  tests/e2e/signalling/mod.rs
Labels: feature, k::api, k::design

#133 Refactor 'metrics' module in Medea (#27)
  Cargo.lock
  src/signalling/peers/metrics/flowing_detector.rs
  src/signalling/peers/metrics/mod.rs
  src/signalling/peers/metrics/quality_meter.rs
  src/signalling/peers/mod.rs
  src/signalling/peers/traffic_watcher.rs
  src/signalling/room/command_handler.rs
Labels: enhancement, k::design, k::monitoring, k::refactor

#135 Upgrade Cargo dependencies (#27)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config.toml
  jason/Cargo.toml
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/rpc/mod.rs
  jason/tests/rpc/mod.rs
  src/api/control/callback/clients/grpc.rs
  src/api/control/callback/clients/mod.rs
  src/api/control/callback/service.rs
  src/conf/control.rs
  src/conf/log.rs
  src/conf/media.rs
  src/conf/mod.rs
  src/conf/rpc.rs
  src/conf/server.rs
  src/conf/shutdown.rs
  src/conf/turn.rs
  src/signalling/peers/traffic_watcher.rs
  src/turn/coturn_metrics.rs
  src/turn/service.rs
Labels: enhancement, k::config, k::refactor

#136 Implement WebSocket broadcast in medea-control-api-mock
  mock/control-api/README.md
  mock/control-api/src/api/ws.rs
Labels: feature, k::api, k::testing

#131 Abstract mute state machinery logic (#27)
  Cargo.lock
  Makefile
  jason/src/api/room.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/mute_state/controller.rs
  jason/src/peer/media/mute_state/mod.rs
  jason/src/peer/media/receiver.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
Labels: enhancement, k::design, k::refactor

#137 Add facingMode constraint configuration to Jason (#27)
  .clippy.toml
  Cargo.lock
  jason/CHANGELOG.md
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/lib.rs
  jason/src/media/constraints.rs
  jason/src/media/mod.rs
Labels: feature, k::api

#140 Fix RpcClient reference leak in Jason (#27)
  jason/src/api/mod.rs
  jason/src/rpc/mod.rs
  jason/tests/api/mod.rs
Labels: enhancement, k::refactor, k::testing

#127 Implement tracks disabling/enabling on subscribers side (#27)
  CHANGELOG.md
  jason/CHANGELOG.md
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/e2e-demo/video-call.html
  jason/src/api/room.rs
  jason/src/peer/conn.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver.rs
  jason/src/peer/media/sender.rs
  jason/src/peer/mod.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  jason/tests/web.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/media/peer.rs
  src/media/track.rs
  src/signalling/room/command_handler.rs
  tests/e2e/signalling/track_disable.rs
Labels: feature, k::api, k::design

#141 Update actix Cargo dependencies
  Cargo.lock
  Cargo.toml
  mock/control-api/Cargo.toml
  mock/control-api/src/main.rs
  src/api/client/server.rs
  src/api/client/session.rs
  src/api/control/grpc/server.rs
  src/shutdown.rs
  src/signalling/participants.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
  src/turn/coturn_metrics.rs
  src/utils/mod.rs
Labels: enhancement, k::refactor

#138 Implement ICE restart (#27)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/src/peer/conn.rs
  jason/src/peer/mod.rs
  jason/src/rpc/reconnect_handle.rs
  jason/tests/peer/mod.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/api/control/refs/local_uri.rs
  src/media/peer.rs
  src/signalling/peers/metrics/connection_failure_detector.rs
  src/signalling/peers/metrics/flowing_detector.rs
  src/signalling/peers/metrics/mod.rs
  src/signalling/peers/metrics/quality_meter.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/peer_events_handler.rs
  tests/e2e/signalling/ice_restart.rs
  tests/e2e/signalling/mod.rs
Labels: feature, k::api, k::design

#142 Refactor ControlApiService to more idiomatic async/.await
  Cargo.lock
  src/api/control/grpc/server.rs
Labels: enhancement, k::refactor
