Repository instrumentisto/medea, pull requests merged in 2021-03, with the labels that each got.

#178 Add Medea E2E test runner
  .clippy.toml
  .editorconfig
  .env
  .github/workflows/ci.yml
  .rustfmt.toml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Makefile
  docker-compose.coturn.yml
  docker-compose.medea.yml
  mock/control-api/src/api/endpoint.rs
  mock/control-api/src/api/member.rs
  mock/control-api/src/api/mod.rs
  mock/control-api/src/api/room.rs
  mock/control-api/src/api/ws.rs
  mock/control-api/src/lib.rs
  mock/control-api/src/main.rs
  tests/e2e/browser/client.rs
  tests/e2e/browser/js.rs
  tests/e2e/browser/mod.rs
  tests/e2e/conf.rs
  tests/e2e/control.rs
  tests/e2e/docker-compose.host.yml
  tests/e2e/docker-compose.yml
  tests/e2e/features/on_new_connection_fires.feature
  tests/e2e/index.html
  tests/e2e/main.rs
  tests/e2e/nginx.conf
  tests/e2e/object/connection.rs
  tests/e2e/object/connections_store.rs
  tests/e2e/object/jason.rs
  tests/e2e/object/mod.rs
  tests/e2e/object/room.rs
  tests/e2e/steps/connection.rs
  tests/e2e/steps/media_state.rs
  tests/e2e/steps/mod.rs
  tests/e2e/world/member.rs
  tests/e2e/world/mod.rs
  tests/integration/callbacks/member.rs
  tests/integration/callbacks/mod.rs
  tests/integration/grpc_control_api/create.rs
  tests/integration/grpc_control_api/credentials.rs
  tests/integration/grpc_control_api/delete.rs
  tests/integration/grpc_control_api/mod.rs
  tests/integration/grpc_control_api/rpc_settings.rs
  tests/integration/grpc_control_api/signaling.rs
  tests/integration/main.rs
  tests/integration/signalling/add_endpoints_synchronization.rs
  tests/integration/signalling/command_validation.rs
  tests/integration/signalling/ice_restart.rs
  tests/integration/signalling/mod.rs
  tests/integration/signalling/pub_sub_signallng.rs
  tests/integration/signalling/rpc_settings.rs
  tests/integration/signalling/three_pubs.rs
  tests/integration/signalling/track_disable.rs
  tests/integration/signalling/track_mute.rs
Labels: feature, k::testing, k::toolchain

#185 Enable 'clippy::must_use_candidate' lint
  Cargo.lock
  jason/src/api/connection.rs
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/lib.rs
  jason/src/media/constraints.rs
  jason/src/media/device_info.rs
  jason/src/media/manager.rs
  jason/src/media/mod.rs
  jason/src/media/track/local.rs
  jason/src/media/track/remote.rs
  jason/src/rpc/backoff_delayer.rs
  jason/src/rpc/heartbeat.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/reconnect_handle.rs
  jason/src/rpc/websocket/transport.rs
  jason/src/utils/errors.rs
  jason/src/utils/mod.rs
  proto/client-api/src/lib.rs
  src/api/client/rpc_connection.rs
  src/api/control/callback/mod.rs
  src/api/control/callback/url.rs
  src/api/control/error_codes.rs
  src/api/control/member.rs
  src/api/control/pipeline.rs
  src/api/control/refs/fid.rs
  src/api/control/refs/impls_for_stateful_refs.rs
  src/api/control/refs/local_uri.rs
  src/api/control/room.rs
  src/conf/log.rs
  src/conf/server.rs
  src/conf/turn.rs
  src/lib.rs
  src/media/peer.rs
  src/shutdown.rs
  src/signalling/elements/endpoints/mod.rs
  src/signalling/elements/endpoints/webrtc/play_endpoint.rs
  src/signalling/elements/endpoints/webrtc/publish_endpoint.rs
  src/signalling/elements/member.rs
  src/signalling/participants.rs
  src/signalling/peers/traffic_watcher.rs
  src/signalling/room/mod.rs
  src/signalling/room_service.rs
  src/utils/mod.rs
  tests/e2e/browser/mod.rs
Labels: enhancement, k::refactor

#184 Prepare Jason's error handling for mobile platform support (#182)
  Cargo.lock
  Makefile
  jason/src/api/wasm/constraints_update_exception.rs
  jason/src/api/wasm/jason_error.rs
  jason/src/api/wasm/media_manager_handle.rs
  jason/src/api/wasm/media_stream_settings.rs
  jason/src/api/wasm/mod.rs
  jason/src/api/wasm/reconnect_handle.rs
  jason/src/api/wasm/room_handle.rs
  jason/src/connection.rs
  jason/src/media/manager.rs
  jason/src/peer/mod.rs
  jason/src/platform/mod.rs
  jason/src/platform/peer_connection.rs
  jason/src/platform/wasm/peer_connection.rs
  jason/src/platform/wasm/transport.rs
  jason/src/room.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/reconnect_handle.rs
  jason/src/rpc/websocket/client.rs
  jason/src/utils/component.rs
  jason/src/utils/errors.rs
  jason/src/utils/mod.rs
Labels: enhancement, k::api, k::design, k::refactor

#180 Add E2E tests for Control API
  .github/workflows/ci.yml
  Cargo.lock
  mock/control-api/src/api/endpoint.rs
  mock/control-api/src/api/mod.rs
  mock/control-api/src/callback/mod.rs
  src/api/client/session.rs
  src/api/mod.rs
  src/media/peer.rs
  src/signalling/peers/mod.rs
  src/signalling/room/peer_events_handler.rs
  src/signalling/room/rpc_server.rs
  tests/e2e/browser/client.rs
  tests/e2e/browser/js.rs
  tests/e2e/conf.rs
  tests/e2e/control.rs
  tests/e2e/features/create_endpoint.feature
  tests/e2e/features/media_disable.feature
  tests/e2e/features/media_mute.feature
  tests/e2e/features/on_join.feature
  tests/e2e/features/on_leave.feature
  tests/e2e/features/remote_connection_close.feature
  tests/e2e/object/jason.rs
  tests/e2e/object/tracks_store.rs
  tests/e2e/steps/control_api.rs
  tests/e2e/steps/mod.rs
  tests/e2e/steps/track.rs
  tests/e2e/world/member.rs
  tests/e2e/world/mod.rs
Labels: enhancement, feature, k::testing

#186 Add E2E tests for state synchronization on RPC reconnection
  Cargo.lock
  Makefile
  tests/e2e/browser/mock/mod.rs
  tests/e2e/browser/mock/websocket.rs
  tests/e2e/browser/mod.rs
  tests/e2e/features/state_synchronization.feature
  tests/e2e/index.html
  tests/e2e/object/jason.rs
  tests/e2e/object/room.rs
  tests/e2e/steps/mod.rs
  tests/e2e/steps/websocket.rs
  tests/e2e/world/member.rs
  tests/e2e/world/mod.rs
Labels: feature, k::testing

#139 Rename Event::TracksUpdated to Event::PeerUpdated (#27)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/rfc/0002-webrtc-client-api.md
  jason/CHANGELOG.md
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/tests/api/room.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/media/peer.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/mod.rs
  src/signalling/room/peer_events_handler.rs
  tests/integration/grpc_control_api/create.rs
  tests/integration/signalling/add_endpoints_synchronization.rs
  tests/integration/signalling/ice_restart.rs
  tests/integration/signalling/mod.rs
  tests/integration/signalling/track_disable.rs
  tests/integration/signalling/track_mute.rs
Labels: enhancement, k::api, k::refactor

#188 Add E2E tests for the getUserMedia request
  Cargo.lock
  tests/e2e/browser/mock/media_devices.rs
  tests/e2e/browser/mock/mod.rs
  tests/e2e/features/get_user_media.feature
  tests/e2e/object/jason.rs
  tests/e2e/object/room.rs
  tests/e2e/object/tracks_store.rs
  tests/e2e/steps/media_state.rs
  tests/e2e/steps/room.rs
  tests/e2e/steps/track.rs
  tests/e2e/world/member.rs
Labels: feature, k::testing

#189 Upgrade stable Rust to 1.51 version
  Cargo.lock
  Cargo.toml
  Makefile
  crates/medea-coturn-telnet-client/Cargo.toml
  crates/medea-macro/Cargo.toml
  crates/medea-reactive/Cargo.toml
  crates/medea-reactive/src/subscribers_store/progressable/processed.rs
  jason/Cargo.toml
  jason/src/media/track/local.rs
  jason/src/media/track/remote.rs
  jason/src/peer/conn.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/sender/mod.rs
  jason/src/peer/mod.rs
  jason/src/utils/mod.rs
  mock/control-api/Cargo.toml
  mock/control-api/src/api/endpoint.rs
  mock/control-api/src/api/mod.rs
  mock/control-api/src/api/ws.rs
  mock/control-api/src/callback/server.rs
  mock/control-api/src/client.rs
  mock/control-api/src/lib.rs
  proto/client-api/Cargo.toml
  proto/control-api/Cargo.toml
  src/api/control/callback/mod.rs
  src/api/control/endpoints/mod.rs
  src/api/control/endpoints/webrtc_publish_endpoint.rs
  src/api/control/error_codes.rs
  src/api/control/grpc/server.rs
  src/api/control/member.rs
  src/api/control/mod.rs
  src/conf/server.rs
  src/main.rs
  src/media/peer.rs
  src/signalling/elements/endpoints/mod.rs
  src/signalling/elements/endpoints/webrtc/play_endpoint.rs
  src/signalling/elements/endpoints/webrtc/publish_endpoint.rs
  src/signalling/elements/member.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room_repo.rs
  tests/integration/signalling/track_disable.rs
Labels: enhancement, k::documentation, k::refactor, k::toolchain

#109 Implement MediaTracks removing (#27)
  .clippy.toml
  CHANGELOG.md
  Makefile
  jason/CHANGELOG.md
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/api/room.rs
  jason/src/media/manager.rs
  jason/src/media/track/remote.rs
  jason/src/peer/component/mod.rs
  jason/src/peer/component/tracks_repository.rs
  jason/src/peer/component/watchers.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver/mod.rs
  jason/src/peer/media/sender/mod.rs
  jason/src/peer/mod.rs
  jason/src/peer/transceiver.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  src/api/control/error_codes.rs
  src/media/peer.rs
  src/signalling/elements/endpoints/webrtc/publish_endpoint.rs
  src/signalling/participants.rs
  src/signalling/peers/metrics/flowing_detector.rs
  src/signalling/peers/metrics/quality_meter.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  src/signalling/room/peer_events_handler.rs
  src/signalling/room/rpc_server.rs
  tests/e2e/features/delete_endpoint.feature
  tests/e2e/features/get_user_media.feature
  tests/e2e/features/state_synchronization.feature
  tests/e2e/object/tracks_store.rs
  tests/e2e/steps/control_api.rs
  tests/e2e/steps/track.rs
  tests/e2e/world/mod.rs
  tests/integration/signalling/three_pubs.rs
Labels: enhancement, k::api
