Repository instrumentisto/medea, pull requests merged in 2021-01, with the labels that each got.

#168 Operate hashed Member credentials (#165, #27)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  _dev/specs/all-media-types-required-call.yml
  _dev/specs/audio-call.yml
  _dev/specs/pub-pub-video-call.yml
  _dev/specs/pub-sub-video-call.yml
  _dev/specs/relay-pub-pub-video-call.yml
  _dev/specs/three-members-conference.yml
  _dev/specs/video-call-1.yml
  jason/demo/index.html
  jason/e2e-demo/js/index.js
  jason/src/api/room.rs
  jason/src/rpc/mod.rs
  jason/src/rpc/rpc_session.rs
  jason/tests/api/mod.rs
  jason/tests/rpc/rpc_session.rs
  jason/tests/web.rs
  mock/control-api/src/api/member.rs
  proto/control-api/src/grpc/api.proto
  proto/control-api/src/grpc/api.rs
  proto/control-api/src/grpc/callback.rs
  src/api/control/member.rs
  src/api/control/room.rs
  src/signalling/elements/member.rs
  src/signalling/participants.rs
  src/signalling/peers/mod.rs
  src/signalling/room/rpc_server.rs
  src/signalling/room_service.rs
  tests/e2e/callbacks/member.rs
  tests/e2e/grpc_control_api/create.rs
  tests/e2e/grpc_control_api/credentials.rs
  tests/e2e/grpc_control_api/mod.rs
  tests/e2e/grpc_control_api/rpc_settings.rs
  tests/e2e/grpc_control_api/signaling.rs
  tests/e2e/signalling/add_endpoints_synchronization.rs
  tests/e2e/signalling/command_validation.rs
  tests/e2e/signalling/ice_restart.rs
  tests/e2e/signalling/mod.rs
  tests/e2e/signalling/pub_sub_signallng.rs
  tests/e2e/signalling/rpc_settings.rs
  tests/e2e/signalling/three_pubs.rs
  tests/e2e/signalling/track_disable.rs
  tests/e2e/signalling/track_mute.rs
  tests/specs/pub-sub-video-call.yml
  tests/specs/three-members-conference.yml
Labels: enhancement, feature, k::api, k::design, k::security

#169 Add #[watchable] macro to 'medea-macro' crate (#27, #47)
  crates/medea-macro/CHANGELOG.md
  crates/medea-macro/src/lib.rs
  crates/medea-macro/src/watchers.rs
  jason/src/utils/component.rs
  jason/src/utils/mod.rs
Labels: feature, k::design, k::refactor

#170 Fix Progressable::when_all_processed()'s join_all() bug (#27)
  Cargo.lock
  crates/medea-reactive/CHANGELOG.md
  crates/medea-reactive/src/collections/hash_map.rs
  crates/medea-reactive/src/collections/hash_set.rs
  crates/medea-reactive/src/collections/vec.rs
  crates/medea-reactive/src/field/mod.rs
  crates/medea-reactive/src/field/progressable_cell.rs
  crates/medea-reactive/src/lib.rs
  crates/medea-reactive/src/subscribers_store/progressable/mod.rs
  crates/medea-reactive/src/subscribers_store/progressable/processed.rs
Labels: enhancement, feature, k::api, k::refactor

#164 Migrate events handling to reactivity in 'medea-jason' crate (#27, #47)
  Cargo.toml
  Makefile
  crates/medea-reactive/src/subscribers_store/progressable/guarded.rs
  jason/Cargo.toml
  jason/src/api/mod.rs
  jason/src/api/room.rs
  jason/src/peer/component.rs
  jason/src/peer/conn.rs
  jason/src/peer/local_sdp.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver/component.rs
  jason/src/peer/media/receiver/mod.rs
  jason/src/peer/media/sender/component.rs
  jason/src/peer/media/sender/mod.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/peer/stats.rs
  jason/src/utils/errors.rs
  jason/src/utils/mod.rs
  jason/src/utils/resettable_delay.rs
  jason/tests/api/mod.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  proto/client-api/src/lib.rs
  src/signalling/room/command_handler.rs
  tests/e2e/signalling/command_validation.rs
  tests/e2e/signalling/ice_restart.rs
  tests/e2e/signalling/mod.rs
  tests/e2e/signalling/pub_sub_signallng.rs
Labels: enhancement, k::design, k::refactor

#172 Refactor with wider type parameter defaults usage
  crates/medea-reactive/src/collections/hash_map.rs
  crates/medea-reactive/src/collections/hash_set.rs
  crates/medea-reactive/src/collections/vec.rs
  crates/medea-reactive/src/field/mod.rs
  crates/medea-reactive/src/field/progressable_cell.rs
  crates/medea-reactive/src/subscribers_store/progressable/mod.rs
  crates/medea-reactive/src/subscribers_store/progressable/processed.rs
  jason/src/peer/component.rs
  jason/src/peer/media/receiver/component.rs
  jason/src/peer/media/sender/component.rs
  src/api/control/callback/clients/mod.rs
  src/shutdown.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
  src/turn/coturn_metrics.rs
Labels: enhancement, k::refactor

#173 Remove !muted check on media tracks after getUserMedia()/getDisplayMedia() (#27)
  Cargo.lock
  jason/src/media/manager.rs
Labels: k::api, rollback

#175 Kick Member instead of closing Room on internal errors (#27)
  Cargo.lock
  jason/tests/peer/mod.rs
  mock/control-api/src/callback/mod.rs
  proto/control-api/src/grpc/callback.proto
  proto/control-api/src/grpc/callback.rs
  src/api/client/session.rs
  src/api/control/callback/mod.rs
  src/api/control/error_codes.rs
  src/signalling/participants.rs
  src/signalling/peers/mod.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  src/signalling/room/peer_events_handler.rs
  src/signalling/room/rpc_server.rs
Labels: enhancement, k::api, k::design

#176 Remove Coturn credentials on IceUser drop in Medea (#27)
  jason/tests/peer/mod.rs
  src/api/control/member.rs
  src/signalling/room/dynamic_api.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
  src/turn/cli.rs
  src/turn/ice_user.rs
  src/turn/repo.rs
  src/turn/service.rs
  src/utils/mod.rs
Labels: enhancement, k::refactor, k::security

#174 Fully migrate MediaStates management to reactivity (#27, #47)
  Cargo.lock
  Cargo.toml
  Makefile
  jason/Cargo.toml
  jason/src/api/room.rs
  jason/src/media/constraints.rs
  jason/src/media/manager.rs
  jason/src/peer/component.rs
  jason/src/peer/local_sdp.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver/component.rs
  jason/src/peer/media/receiver/mod.rs
  jason/src/peer/media/sender/component.rs
  jason/src/peer/media/sender/mod.rs
  jason/src/peer/media/transitable_state/controller.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/peer/transceiver.rs
  jason/src/utils/component.rs
  jason/tests/api/mod.rs
  jason/tests/api/room.rs
  jason/tests/peer/media.rs
  jason/tests/peer/mod.rs
  src/media/peer.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  tests/e2e/signalling/track_disable.rs
Labels: enhancement, feature, k::api, k::design, k::refactor

#177 Use getDisplayMedia() and DisplayMediaStreamConstraints from 'web_sys' crate (#27)
  Cargo.lock
  jason/Cargo.toml
  jason/src/media/constraints.rs
  jason/src/media/manager.rs
Labels: enhancement, k::refactor

#167 Implement state synchronization on reconnection (#27, #47)
  CHANGELOG.md
  Cargo.lock
  Makefile
  crates/medea-reactive/src/collections/hash_map.rs
  jason/CHANGELOG.md
  jason/src/api/room.rs
  jason/src/peer/component.rs
  jason/src/peer/component/ice_candidates.rs
  jason/src/peer/component/local_sdp.rs
  jason/src/peer/component/mod.rs
  jason/src/peer/component/tracks_repository.rs
  jason/src/peer/component/watchers.rs
  jason/src/peer/conn.rs
  jason/src/peer/media/mod.rs
  jason/src/peer/media/receiver/component.rs
  jason/src/peer/media/receiver/mod.rs
  jason/src/peer/media/sender/component.rs
  jason/src/peer/media/sender/mod.rs
  jason/src/peer/media/transitable_state/controller.rs
  jason/src/peer/mod.rs
  jason/src/peer/repo.rs
  jason/src/rpc/rpc_session.rs
  jason/src/rpc/websocket/client.rs
  jason/src/utils/component.rs
  jason/src/utils/mod.rs
  jason/src/utils/resettable_delay.rs
  jason/tests/api/room.rs
  jason/tests/peer/media/mod.rs
  jason/tests/peer/media/transitable_state/controller.rs
  jason/tests/peer/media/transitable_state/mod.rs
  jason/tests/peer/mod.rs
  jason/tests/utils/resettable_delay.rs
  proto/client-api/CHANGELOG.md
  proto/client-api/src/lib.rs
  proto/client-api/src/state.rs
  src/api/client/mod.rs
  src/api/client/rpc_connection.rs
  src/api/client/server.rs
  src/api/client/session.rs
  src/api/mod.rs
  src/media/peer.rs
  src/media/track.rs
  src/signalling/peers/metrics/flowing_detector.rs
  src/signalling/peers/mod.rs
  src/signalling/room/command_handler.rs
  src/signalling/room/mod.rs
  src/signalling/room/rpc_server.rs
  tests/e2e/signalling/mod.rs
Labels: enhancement, feature, k::api, k::design
